/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Specialty = IDL.Variant({
  'engineer' : IDL.Null,
  'architect' : IDL.Null,
  'contractor' : IDL.Null,
  'carpenter' : IDL.Null,
});
export const Professional = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'serviceDescription' : IDL.Text,
  'experience' : IDL.Nat,
  'specialty' : Specialty,
});
export const Category = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
  'renovation' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'category' : Category,
  'budgetRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseProfessionals' : IDL.Func(
      [IDL.Opt(Specialty), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Professional)],
      ['query'],
    ),
  'browseProjects' : IDL.Func(
      [IDL.Opt(Category), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'createProfessionalProfile' : IDL.Func(
      [IDL.Text, Specialty, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProfessionalProfile' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfessional' : IDL.Func([IDL.Nat], [IDL.Opt(Professional)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat), Category],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProfessionalProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, Specialty, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat), Category],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Specialty = IDL.Variant({
    'engineer' : IDL.Null,
    'architect' : IDL.Null,
    'contractor' : IDL.Null,
    'carpenter' : IDL.Null,
  });
  const Professional = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'serviceDescription' : IDL.Text,
    'experience' : IDL.Nat,
    'specialty' : Specialty,
  });
  const Category = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
    'renovation' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'category' : Category,
    'budgetRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseProfessionals' : IDL.Func(
        [IDL.Opt(Specialty), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Professional)],
        ['query'],
      ),
    'browseProjects' : IDL.Func(
        [IDL.Opt(Category), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'createProfessionalProfile' : IDL.Func(
        [IDL.Text, Specialty, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProfessionalProfile' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfessional' : IDL.Func([IDL.Nat], [IDL.Opt(Professional)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat), Category],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProfessionalProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, Specialty, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat), Category],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };