/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'commercial' : null } |
  { 'residential' : null } |
  { 'renovation' : null };
export interface Professional {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'serviceDescription' : string,
  'experience' : bigint,
  'specialty' : Specialty,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'category' : Category,
  'budgetRange' : [bigint, bigint],
}
export type Specialty = { 'engineer' : null } |
  { 'architect' : null } |
  { 'contractor' : null } |
  { 'carpenter' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseProfessionals' : ActorMethod<
    [[] | [Specialty], [] | [bigint]],
    Array<Professional>
  >,
  'browseProjects' : ActorMethod<
    [[] | [Category], [] | [bigint], [] | [bigint]],
    Array<Project>
  >,
  'createProfessionalProfile' : ActorMethod<
    [string, Specialty, bigint, string],
    bigint
  >,
  'deleteProfessionalProfile' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfessional' : ActorMethod<[bigint], [] | [Professional]>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postProject' : ActorMethod<
    [string, string, [bigint, bigint], Category],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProfessionalProfile' : ActorMethod<
    [bigint, string, Specialty, bigint, string],
    undefined
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, [bigint, bigint], Category],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];